apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data: # accept in base64 only use echo -n <PASSWORD> | base64 to convert it in terminal
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==